### ISSUE TITLE
'utf8' codec can't decode byte 0xe9 in position 50: invalid continuation byte

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/log-offload#9]
```
2018-03-11 20:39:39.759 CET
Queue: log-offload (/base/data/home/apps/e~rogerthat-server/20180309t111501.408180415363870295/add_1_monkey_patches.py:341)
deferred.run(log_offload.log_offload._export_logs,
             'log-monitoring',
             'rogerthat-server',
             '[XX-OFFLOADv1]',
             'log_offload',
             Key('OffloadRun', 5737611108810752, namespace='log_offload'))

2018-03-11 20:39:40.236 CET
Fetching logs with offset None for versions ['20180307t132021', '20180308t143812', '20180309t103101', '20180309t111501', 'ah-builtin-python-bundle'] (/base/data/home/apps/e~rogerthat-server/20180309t111501.408180415363870295/lib/log_offload/log_offload.py:82)

2018-03-11 20:43:42.955 CET
'utf8' codec can't decode byte 0xe9 in position 50: invalid continuation byte (/base/data/home/apps/e~rogerthat-server/20180309t111501.408180415363870295/add_1_monkey_patches.py:125)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/data/home/apps/e~rogerthat-server/20180309t111501.408180415363870295/add_1_monkey_patches.py", line 346, in _new_deferred_run
    return func(*args, **kwds)
  File "/base/data/home/apps/e~rogerthat-server/20180309t111501.408180415363870295/lib/log_offload/log_offload.py", line 147, in _export_logs
    gcs_file_handle.write(json.dumps({'type': '_request', 'data': request_info}))
  File "/base/data/home/apps/e~rogerthat-server/20180309t111501.408180415363870295/add_1_monkey_patches.py", line 257, in _new_json_dumps
    return _orig_json_dumps(*args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_dist/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_dist/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_dist/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 50: invalid continuation byte
```

**Comment by bart-at-mobicage** [comment]
Cannot json encode request: {'status': 204, 'latency': 0.0074070000000000004, 'resource': '/si/4p2339NGjAVEcp3xuVgS_yKmT2V9DA3lXPTPvBm4Bis-/5649050225344512', 'task_name': None, 'ip': '195.130.155.140', 'start_time': 1521120741.3803549, 'app_id': 'e~rogerthat-server', 'host': 'rogerthat-server.appspot.com', 'mcycles': 0L, 'end_time': 1521120741.3877621, 'response_size': 10307L, 'pending_time': 0.0, 'task_queue_name': None, 'user_agent': 'WHTTPFileDownload_BoxyPlayer_PID000453_BNL0403_Caf\xe9_Lange_Jan_-_Enkhuizen'} (/base/data/home/apps/e~rogerthat-server/20180313t142810.408276300923206775/lib/log_offload/log_offload.py:151)

**Comment by lucasvanhalst** [comment]
Pretty sure this was fixed
